apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate # Ensure we don't have multiple instances running at once
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "1.20.4"
            - name: MEMORY
              value: "2G"
            - name: DIFFICULTY
              value: "normal"
            - name: MODE
              value: "survival"
            - name: ALLOW_NETHER
              value: "true"
            - name: ENABLE_COMMAND_BLOCK
              value: "true"
            - name: ENABLE_RCON
              value: "true"
            - name: RCON_PASSWORD
              value: "minecraft" # In production, use a SecretKeyRef
            - name: MOTD
              value: "Minecraft Server - Powered by Kubernetes"
          ports:
            - containerPort: 25565
              name: minecraft
            - containerPort: 25575
              name: rcon
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "2"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  labels:
    app: minecraft
spec:
  type: LoadBalancer # Change to NodePort for local deployments
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: minecraft
  selector:
    app: minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-pvc
  labels:
    app: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard # Adjust based on your K8s environment
